version: "3.5"

services:
  go1.19-build:
    container_name: go1.19-build-v2
    image: go1.19-build-v2
    build:
      context: .
      dockerfile: ../../Dockerfile
    restart: always
    tty: true
    volumes:
      - ${PRO_PATH}/:${MOUNT_PRO_PATH}