version: "3.5"

services:
  go1.19:
    container_name: go1.19
    image: go1.19-build-v2
#    build:
#      context: .
#      dockerfile: Dockerfile
    restart: always
    environment:
      - TZ=${TZ}
    tty: true
    volumes:
      - ${GO_PKG_MOD}/:/go/pkg/mod
      - ${PRO_PATH}/:${MOUNT_PRO_PATH}
    networks:
      store:
        ipv4_address: 172.20.2.99
  rpc-api:
    container_name: rpc-api
    image: debian:latest
    ports:
      - "8881:8080"
    environment:
      - TZ=${TZ}
      - LANG=${LANG}
    volumes:
      - ${APP_PATH}/rpc/api/bin/rpc_api.bin:${MOUNT_PATH}/rpc_api.bin
      - ${APP_PATH}/rpc/api/etc:${MOUNT_PATH}/etc
      - ${APP_PATH}/tmp/:${MOUNT_PATH}/tmp
      - ${APP_PATH}/yaml/:${MOUNT_PATH}/yaml
      - ${APP_PATH}/common/:${MOUNT_PATH}/common
    command: /bin/bash -c "cd /var/www/store&&./rpc_api.bin module service >> tmp/rpc-api.err"
    networks:
      store:
        ipv4_address: 172.20.2.100
  rpc-socket:
    container_name: rpc-socket
    image: debian:latest
    ports:
      - "8882:8080"
    environment:
      - TZ=${TZ}
      - LANG=${LANG}
    volumes:
      - ${APP_PATH}/rpc/socket/bin/rpc_socket.bin:${MOUNT_PATH}/rpc_socket.bin
      - ${APP_PATH}/rpc/socket/etc:${MOUNT_PATH}/etc
      - ${APP_PATH}/tmp/:${MOUNT_PATH}/tmp
      - ${APP_PATH}/yaml/:${MOUNT_PATH}/yaml
      - ${APP_PATH}/common/:${MOUNT_PATH}/common
    command: /bin/bash -c "cd /var/www/store&&./rpc_socket.bin module service >> tmp/rpc-socket.err"
    networks:
      store:
        ipv4_address: 172.20.2.102
  api:
    container_name: api
    #使用别人的构造器
    image: debian:latest
#    build:
#      context: ${APP_PATH}
#      dockerfile: api/Dockerfile
    ports:
      - "7000:8888"
    environment:
      - TZ=${TZ}
      - LANG=${LANG}
    volumes:
      - ${APP_PATH}/api/bin/api.bin:${MOUNT_PATH}/api.bin
      - ${APP_PATH}/api/etc:${MOUNT_PATH}/etc
      - ${APP_PATH}/tmp/:${MOUNT_PATH}/tmp
      - ${APP_PATH}/yaml/:${MOUNT_PATH}/yaml
      - ${APP_PATH}/common/:${MOUNT_PATH}/common
    command: /bin/bash -c "cd /var/www/store&&./api.bin module api >> tmp/api.err"
    networks:
      store:
        ipv4_address: 172.20.2.101
  websocket-1:
    container_name: websocket-1
    #使用别人的构造器
    image: debian:latest
    #    build:
    #      context: ${APP_PATH}
    #      dockerfile: api/Dockerfile
    ports:
      - "6991:8888"
    environment:
      - TZ=${TZ}
      - LANG=${LANG}
    volumes:
      - ${APP_PATH}/websocket/bin/websocket.bin:${MOUNT_PATH}/websocket.bin
      - ${APP_PATH}/websocket/etc:${MOUNT_PATH}/etc
      - ${APP_PATH}/tmp/:${MOUNT_PATH}/tmp
      - ${APP_PATH}/yaml/:${MOUNT_PATH}/yaml
      - ${APP_PATH}/common/:${MOUNT_PATH}/common
    command: /bin/bash -c "cd /var/www/store&&./websocket.bin module websocket >> tmp/websocket.err"
    networks:
      store:
        ipv4_address: 172.20.2.198
networks:
  store:
    name: store
    driver: bridge
#    ipam:
#      config:
#        - subnet: 172.20.2.0/24 #建议填写宿主机的网关
#          gateway: 172.20.2.1