// Code generated by goctl. DO NOT EDIT.
// Source: api.proto

package roles

import (
	"context"

	"k/rpc/api/pb/api"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ReqRolesReq = api.ReqRolesReq
	ReqRolesRes = api.ReqRolesRes
	ReqUser     = api.ReqUser
	ResUser     = api.ResUser

	Roles interface {
		GetRolesList(ctx context.Context, in *ReqRolesReq, opts ...grpc.CallOption) (*ReqRolesRes, error)
	}

	defaultRoles struct {
		cli zrpc.Client
	}
)

func NewRoles(cli zrpc.Client) Roles {
	return &defaultRoles{
		cli: cli,
	}
}

func (m *defaultRoles) GetRolesList(ctx context.Context, in *ReqRolesReq, opts ...grpc.CallOption) (*ReqRolesRes, error) {
	client := api.NewRolesClient(m.cli.Conn())
	return client.GetRolesList(ctx, in, opts...)
}
