// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"store/websocket/internal/svc"
	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(s *rest.Server, serverCtx *svc.ServiceContext) {
	s.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/conn/test",
				Handler: TestConnHandler(serverCtx),
			},
		},
	)
}
