// Code generated by goctl. DO NOT EDIT.
// Source: api.proto

package server

import (
	"context"

	"store/rpc/api/internal/logic/roles"
	"store/rpc/api/internal/svc"
	"store/rpc/api/pb/api"
)

type RolesServer struct {
	svcCtx *svc.ServiceContext
	api.UnimplementedRolesServer
}

func NewRolesServer(svcCtx *svc.ServiceContext) *RolesServer {
	return &RolesServer{
		svcCtx: svcCtx,
	}
}

func (s *RolesServer) GetRolesList(ctx context.Context, in *api.ReqRolesReq) (*api.ReqRolesRes, error) {
	l := roleslogic.NewGetRolesListLogic(ctx, s.svcCtx)
	return l.GetRolesList(in)
}
