// Code generated by goctl. DO NOT EDIT.
// Source: api.proto

package user

import (
	"context"

	"k/rpc/api/pb/api"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ReqRolesReq = api.ReqRolesReq
	ReqRolesRes = api.ReqRolesRes
	ReqUser     = api.ReqUser
	ResUser     = api.ResUser

	User interface {
		GetUser(ctx context.Context, in *ReqUser, opts ...grpc.CallOption) (*ResUser, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) GetUser(ctx context.Context, in *ReqUser, opts ...grpc.CallOption) (*ResUser, error) {
	client := api.NewUserClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}
